[package]
name = "radiance"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.4.0"
lazy_static = "*"
ndarray = {version = "*", features = ["approx"]}
ndarray-rand = "0.14.0"
num-traits = "*"
rand = "*"
topological-sort = "*"
